import { createRequire } from 'node:module';
const require=createRequire(import.meta.url);
const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const ts=require('typescript');
for(const [project,file,key,choice] of [['aeo-measurement-release','artifacts/geo-seo-tool/src/lib/analytics.ts','aeo.trackingConsent','all']]){
function runtime(gpc=false){const storage=new Map();const nodes=new Map();const win={location:{pathname:'/privacy',search:'?email=private@example.com',href:'https://example.com/privacy?email=private@example.com',origin:'https://example.com'},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},dispatchEvent(){}};const ctx={exports:{},window:win,navigator:{globalPrivacyControl:gpc},document:{title:'Privacy',referrer:'https://example.com/?token=secret',getElementById:k=>nodes.get(k),createElement:()=>({}),head:{appendChild:n=>nodes.set(n.id,n)}},CustomEvent:class{},URLSearchParams,URL,Date};let source=fs.readFileSync(new URL('../../../'+file,import.meta.url),'utf8').replaceAll('import.meta.env','({PROD:true})');vm.runInNewContext(ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,ctx);return {api:ctx.exports,win,nodes};}
test(project+' consent, PII, dedup and GPC',()=>{let r=runtime();r.api.initializeAnalytics();assert.equal(r.nodes.size,0);r.api.setTrackingConsent(choice);r.api.trackPageView('/privacy?email=private@example.com');r.api.trackPageView('/privacy?email=other@example.com');r.api.trackEvent('sign_up',{method:'email',email:'private@example.com',page_location:'https://evil.com/?token=secret',source:'private@example.com'});assert.ok(r.win.dataLayer.every(v=>Object.prototype.toString.call(v)==="[object Arguments]"));const calls=r.win.dataLayer.map(v=>Array.from(v));assert.equal(calls.filter(v=>v[1]==='page_view').length,1);const event=calls.find(v=>v[1]==='sign_up');assert.equal(event[2].method,'email');assert.equal(event[2].email,undefined);assert.equal(event[2].page_location,'https://example.com/privacy');assert.ok(!JSON.stringify(calls).includes('private@example.com'));r.win.gtag=()=>{throw new Error('vendor blocked')};assert.doesNotThrow(()=>r.api.trackEvent('sign_up',{method:'email'}));assert.ok(calls.every(v=>Object.prototype.toString.call(v)==='[object Array]'));r=runtime(true);r.api.setTrackingConsent(choice);r.api.trackEvent('sign_up');assert.equal(r.nodes.size,0);assert.equal(r.win.dataLayer.map(v=>Array.from(v)).filter(v=>v[0]==='event').length,0);});
}

test("accepted registration contract rejects false success",()=>{
 const ctx={exports:{},URL};vm.runInNewContext(ts.transpileModule(fs.readFileSync(new URL('../../../artifacts/geo-seo-tool/src/lib/accepted-registration.ts',import.meta.url),"utf8"),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,ctx);
 for(const rejected of [null,{},true,{accepted:"true"},{accepted:false}]) assert.equal(ctx.exports.isAcceptedRegistration(rejected),false);assert.equal(ctx.exports.isAcceptedRegistration({accepted:true}),true);
 for(const rejected of [null,{}, {url:"javascript:alert(1)"},{url:"http://checkout.stripe.com/pay"},{url:"https://user:pass@checkout.stripe.com/pay"}]) assert.equal(ctx.exports.acceptedCheckoutUrl(rejected),null);assert.equal(ctx.exports.acceptedCheckoutUrl({url:"https://checkout.stripe.com/pay/cs_example"}),"https://checkout.stripe.com/pay/cs_example");

});
