import { Link, useLocation } from "wouter";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { SEO, breadcrumbJsonLd } from "@/components/seo";

const guides: Record<string, { title: string; description: string; heading: string; intro: string; sections: Array<{ title: string; body: string }> }> = {
  "/content-effort-for-seo-and-ai-search": {
    title: "Content Effort for SEO and AI Search", description: "A practical framework for creating original, well-documented content that helps people, search engines, and AI systems understand your expertise.", heading: "Content Effort for SEO and AI Search", intro: "Useful content shows its work. That does not mean making a page longer. It means giving readers a clear answer, original information they cannot get from a generic summary, and enough context to trust the advice.", sections: [
      { title: "What Content Effort means", body: "Content Effort is the visible evidence that a page has been edited, researched, tested, organized, and shaped by someone with a point of view. It is not a shortcut to rankings and it is not something a crawler can fully verify." },
      { title: "The five visible signals", body: "Start with editorial curation, first-party information, evidence of work, direct helpful information before filler, and analysis of trade-offs. Use only the signals that are true for the page and document them clearly." },
      { title: "How it supports AI visibility", body: "AI systems need clear facts, provenance, and self-contained answers. A practical example, methodology note, or constraint can make a page easier to interpret than an interchangeable recap of common advice." },
    ],
  },
  "/show-first-party-experience-seo": { title: "How to Show First-Party Experience in SEO Content", description: "Ways to document real experience in SEO content without inventing proof.", heading: "How to Show First-Party Experience in SEO Content", intro: "First-party experience is useful only when it is real and specific. Your job is to make it visible without turning every page into a case study.", sections: [{ title: "Use concrete artifacts", body: "Show a screenshot, workflow, annotated example, customer pattern, or before-and-after decision when you have permission. Explain what changed and what did not." }, { title: "State the scope", body: "Name the audience, inputs, time period, and limitations. This makes a useful example more credible than a broad claim." }, { title: "Keep it relevant", body: "A small example near the decision it supports is more helpful than a long credentials section at the end." }] },
  "/seo-content-quality-vs-filler": { title: "SEO Content Quality vs. Filler Content", description: "How to identify filler and put useful SEO content first.", heading: "SEO Content Quality vs. Filler Content", intro: "Filler is not just extra words. It is text that delays the answer, repeats an obvious point, or fails to help a reader decide what to do next.", sections: [{ title: "Lead with the answer", body: "Open with the conclusion, who it applies to, and the main constraint. Then add the evidence and detail a reader needs." }, { title: "Cut generic scene-setting", body: "Replace broad statements with a specific example, definition, decision rule, or source. If a sentence could appear on any competitor's page, it usually needs work." }, { title: "Preserve useful context", body: "Do not confuse concise writing with thin writing. Keep the caveats, edge cases, and supporting details that change a decision." }] },
  "/create-content-ai-can-cite": { title: "How to Create Content AI Systems Can Cite", description: "Practical steps for making website content clear, attributable, and easy for AI systems to interpret.", heading: "How to Create Content AI Systems Can Cite", intro: "No one can guarantee an AI citation. You can make a page easier to retrieve and evaluate by publishing clear, current, attributable information.", sections: [{ title: "Make the core fact explicit", body: "State what the company does, who it helps, and the problem it solves in plain language. Keep those brand facts consistent across the pages you control." }, { title: "Build self-contained answers", body: "Use descriptive headings followed by short answers that retain enough context to make sense on their own." }, { title: "Show your sources and limits", body: "Link to primary sources where possible and identify where your own experience ends. Credibility comes from specificity, not bigger claims." }] },
  "/content-audit-original-research-checklist": { title: "Content Audit Checklist for Original Research and Evidence", description: "A practical checklist for documenting original research, evidence, and methodology in content.", heading: "Content Audit Checklist for Original Research and Evidence", intro: "Before publishing a research-led page, make it easy for a reader to understand what was actually done and what the evidence can support.", sections: [{ title: "Checklist", body: "Name the question, source of information, sample or scope, collection period, method, limitations, and the decision the evidence supports. Include a table, screenshot, or example when it improves clarity." }, { title: "Avoid overclaiming", body: "Do not make causal claims from a small sample or present a customer anecdote as universal evidence. A useful limitation often makes the page stronger." }, { title: "Keep it current", body: "Add a visible update date and review time-sensitive findings on a real schedule." }] },
  "/document-expertise-methodology": { title: "How to Document Testing, Methodology, and Expertise on Your Website", description: "How to document your methodology and expertise so readers can evaluate your advice.", heading: "How to Document Testing, Methodology, and Expertise on Your Website", intro: "Expertise is more useful when a reader can see how you reached a conclusion and when it may not apply.", sections: [{ title: "Describe the method", body: "Explain the inputs, process, decision criteria, and constraints in plain English. Link to deeper documentation where it helps." }, { title: "Use examples responsibly", body: "Show representative examples and separate observed outcomes from guarantees. Ask permission before publishing customer information." }, { title: "Make authorship visible", body: "Use a named author, relevant background, and an updated date. Keep author pages factual and connected to the work they actually do." }] },
};

export default function ContentEffortGuide() {
  const [location] = useLocation();
  const guide = guides[location] ?? guides["/content-effort-for-seo-and-ai-search"];
  const path = location in guides ? location : "/content-effort-for-seo-and-ai-search";
  const article = { "@context": "https://schema.org", "@type": "Article", headline: guide.heading, description: guide.description, author: { "@type": "Organization", name: "AEO Improvement" }, datePublished: "2026-08-17", dateModified: "2026-08-17", mainEntityOfPage: `https://aeoimprovement.com${path}` };
  return <main className="mx-auto w-full max-w-4xl px-4 py-12 md:py-16">
    <SEO title={`${guide.title} | AEO Improvement`} description={guide.description} path={path} ogType="article" publishedTime="2026-08-17" modifiedTime="2026-08-17" authorName="AEO Improvement" jsonLd={[article, breadcrumbJsonLd([{ name: "Home", path: "/" }, { name: "Resources", path: "/content-effort-for-seo-and-ai-search" }, { name: guide.title, path }])]} />
    <p className="text-sm font-medium text-emerald-700">AEO Improvement resource</p><h1 className="mt-2 text-4xl font-bold tracking-tight">{guide.heading}</h1><p className="mt-4 text-lg text-muted-foreground">{guide.intro}</p><p className="mt-4 text-sm text-muted-foreground">Updated August 17, 2026 · By AEO Improvement</p>
    <div className="mt-10 space-y-5">{guide.sections.map((section) => <Card key={section.title}><CardHeader><CardTitle>{section.title}</CardTitle></CardHeader><CardContent className="leading-7 text-muted-foreground">{section.body}</CardContent></Card>)}</div>
    <Card className="mt-8 border-emerald-200 bg-emerald-50/50"><CardContent className="p-6"><h2 className="font-semibold">Audit your page before you rewrite it</h2><p className="mt-2 text-sm text-muted-foreground">AEO Improvement checks visible technical, content, and AI-readiness signals. Use the results as a prioritized starting point, then validate changes against your real audience and Search Console data.</p><Link href="/free-aeo-audit-tool" className="mt-4 inline-block text-sm font-medium text-emerald-700 hover:underline">Run a free audit</Link></CardContent></Card>
    <p className="mt-8 text-sm text-muted-foreground">Framework credit: <a className="text-emerald-700 hover:underline" href="https://signal.zyppy.com/p/content-effort" target="_blank" rel="noreferrer">Cyrus Shepard and Zyppy Signal's Content Effort framework</a>. This guide adds AEO Improvement's own practical interpretation and does not reproduce the source text.</p>
  </main>;
}
